import type { AdapterCliConfig } from "../adapters/mod.ts";

export const VERSION = "0.1";

export const ADAPTER_CONFIG_SCHEMA_VERSIONS: AdapterCliConfig["version"][] = [
    1,
];

export const GENERATED_FILE_OUTPUT_PREFIX = `\
// This file is auto-generated by grammY i18n CLI ${VERSION}
// Changes made to this file will be overwritten.`;
