// This file is auto-generated by grammY i18n CLI 0.1
// Changes made to this file will be overwritten.

type Value = string | number | Date;

type AvailableLocales = "en";
type Namespaces = "";

type AvailableMessages = {
    "start": never;
    "start.ping-button": never;
    "start.ping-alert": never;
    "status.downloading": {
        "size": Value;
    };
    "status.uploading": never;
    "image-info": {
        "width": Value;
        "height": Value;
        "size": Value;
    };
    "about": {
        "projectUrl": Value;
    };
};

export type GeneratedLocalesTypings = {
    locales: AvailableLocales;
    namespaces: Namespaces;
    messages: AvailableMessages;
};
