// This file is auto-generated by grammY i18n CLI 0.1
// Changes made to this file will be overwritten.

type Value = string | number | Date;

type AvailableLocales = "en" | "ru" | "de";

type AvailableMessages = {
    "message": {
        "theme": Value;
    };
    "message.key": never;
    "message.keyx": never;
    "createx": never;
    "create": never;
    "cooked2.hype": {
        "file2": Value;
    };
    "coo": {
        "lastChecked": Value;
    };
    "coo.k": never;
    "maker": never;
    "pop": never;
    "pxoppy": never;
};

export type GeneratedLocalesTypings = {
    locales: AvailableLocales;
    messages: AvailableMessages;
};
